from dataclasses import dataclass

class RealtimeClientEvent: ...
class ConversationItem: ...
class ConversationItemContent: ...
class ConversationItemCreatedEvent: ...
class ConversationItemCreateEvent: ...
class ConversationItemDeletedEvent: ...
class ConversationItemDeleteEvent: ...
class ConversationItemInputAudioTranscriptionCompletedEvent: ...
class ConversationItemInputAudioTranscriptionFailedEvent: ...
class ConversationItemTruncateEvent: ...
class ErrorEvent: ...
class InputAudioBufferAppendEvent: ...
class InputAudioBufferClearEvent: ...
class InputAudioBufferCommitEvent: ...
class InputAudioBufferSpeechStartedEvent: ...
class InputAudioBufferSpeechStoppedEvent: ...
class ResponseAudioDeltaEvent: ...
class ResponseAudioDoneEvent: ...
class ResponseAudioTranscriptDoneEvent: ...
class ResponseCancelEvent: ...
class ResponseContentPartAddedEvent: ...
class ResponseContentPartDoneEvent: ...
class ResponseCreatedEvent: ...
class ResponseCreateEvent: ...
class ResponseDoneEvent: ...
class ResponseOutputItemAddedEvent: ...
class ResponseOutputItemDoneEvent: ...
class SessionUpdateEvent: ...

session_update_event = None

__all__ = [name for name in globals() if not name.startswith("_")]
