name: Search Fix Agent

on:
  workflow_dispatch:

jobs:
  search-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install ruff pytest
          pip install -e livekit-agents
      - name: Run search and fix agent
        run: python scripts/search_fix_agent.py
